# Generated by Django 2.0.7 on 2018-08-04 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('was_checked', models.IntegerField(default=0)),
                ('was_up', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('uptime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]